name: E2E tests

on:
      push:
        branches:
          - master
      pull_request:
        types: [opened, synchronize, reopened]
        branches:
          - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          build: npm run build
          start: npm start
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Run E2E test
        uses: cypress-io/github-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          config: baseUrl=https://barrigareact.wcaquino.me/